### ISSUE TITLE
Possilble Features

### ISSUE THREAD

**Issue by redusk** [TheMCPEGamer/Adventuria#4]
This is where features that could be added go.
Do we want to have:
- An infinite seamless world or a world that loads levels as you leave the world boundaries (like Zelda; you walk past the world boundaries and are shown a loading screen until the new part is loaded)
- Custom characters
- Multiplayer
- Blocks can only be placed on other blocks

**Comment by MbCrew** [comment]
custom players yes
multiplayer tell me how i will do it
infinite seamless world unless it lags too bad

**Comment by wordandahalf** [comment]
1) We wouldn't really need a whole loading screen, we could just use a chunk system, and when the game is loading new chunks, we could add an animation in the top right corner
2) Like Terraria? If so, then sure!
3) Least of our priorities right now
